-- Schema for CMS SYNPUF sample data (DE 2008 beneficiary / 2008-2010 inpatient claims).
-- Column names are the lowercased CSV headers.

CREATE TABLE IF NOT EXISTS beneficiary (
    desynpuf_id                VARCHAR(16) PRIMARY KEY,
    bene_birth_dt              VARCHAR(8),
    bene_death_dt              VARCHAR(8),
    bene_sex_ident_cd          VARCHAR(2),
    bene_race_cd               VARCHAR(2),
    bene_esrd_ind              VARCHAR(2),
    sp_state_code              VARCHAR(2),
    bene_county_cd             VARCHAR(3),
    bene_hi_cvrage_tot_mons    VARCHAR(2),
    bene_smi_cvrage_tot_mons   VARCHAR(2),
    bene_hmo_cvrage_tot_mons   VARCHAR(2),
    plan_cvrg_mos_num          VARCHAR(2),
    sp_alzhdmta                VARCHAR(2),
    sp_chf                     VARCHAR(2),
    sp_chrnkidn                VARCHAR(2),
    sp_cncr                    VARCHAR(2),
    sp_copd                    VARCHAR(2),
    sp_depressn                VARCHAR(2),
    sp_diabetes                VARCHAR(2),
    sp_ischmcht                VARCHAR(2),
    sp_osteoprs                VARCHAR(2),
    sp_ra_oa                   VARCHAR(2),
    sp_strketia                VARCHAR(2),
    medreimb_ip                NUMERIC(12,2),
    benres_ip                  NUMERIC(12,2),
    pppymt_ip                  NUMERIC(12,2),
    medreimb_op                NUMERIC(12,2),
    benres_op                  NUMERIC(12,2),
    pppymt_op                  NUMERIC(12,2),
    medreimb_car               NUMERIC(12,2),
    benres_car                 NUMERIC(12,2),
    pppymt_car                 NUMERIC(12,2)
);

CREATE TABLE IF NOT EXISTS inpatient_claims (
    desynpuf_id                          VARCHAR(16),
    clm_id                               VARCHAR(16),
    segment                              VARCHAR(2),
    clm_from_dt                          VARCHAR(8),
    clm_thru_dt                          VARCHAR(8),
    prvdr_num                            VARCHAR(6),
    clm_pmt_amt                          NUMERIC(12,2),
    nch_prmry_pyr_clm_pd_amt             NUMERIC(12,2),
    at_physn_npi                         VARCHAR(10),
    op_physn_npi                         VARCHAR(10),
    ot_physn_npi                         VARCHAR(10),
    clm_admsn_dt                         VARCHAR(8),
    admtng_icd9_dgns_cd                  VARCHAR(5),
    clm_pass_thru_per_diem_amt           NUMERIC(12,2),
    nch_bene_ip_ddctbl_amt               NUMERIC(12,2),
    nch_bene_pta_coinsrnc_lblty_am       NUMERIC(12,2),
    nch_bene_blood_ddctbl_lblty_am       NUMERIC(12,2),
    clm_utlztn_day_cnt                   VARCHAR(4),
    nch_bene_dschrg_dt                   VARCHAR(8),
    clm_drg_cd                           VARCHAR(3),
    icd9_dgns_cd_1                       VARCHAR(5),
    icd9_dgns_cd_2                       VARCHAR(5),
    icd9_dgns_cd_3                       VARCHAR(5),
    icd9_dgns_cd_4                       VARCHAR(5),
    icd9_dgns_cd_5                       VARCHAR(5),
    icd9_dgns_cd_6                       VARCHAR(5),
    icd9_dgns_cd_7                       VARCHAR(5),
    icd9_dgns_cd_8                       VARCHAR(5),
    icd9_dgns_cd_9                       VARCHAR(5),
    icd9_dgns_cd_10                      VARCHAR(5),
    icd9_prcdr_cd_1                      VARCHAR(5),
    icd9_prcdr_cd_2                      VARCHAR(5),
    icd9_prcdr_cd_3                      VARCHAR(5),
    icd9_prcdr_cd_4                      VARCHAR(5),
    icd9_prcdr_cd_5                      VARCHAR(5),
    icd9_prcdr_cd_6                      VARCHAR(5),
    hcpcs_cd_1                           VARCHAR(5),
    hcpcs_cd_2                           VARCHAR(5),
    hcpcs_cd_3                           VARCHAR(5),
    hcpcs_cd_4                           VARCHAR(5),
    hcpcs_cd_5                           VARCHAR(5),
    hcpcs_cd_6                           VARCHAR(5),
    hcpcs_cd_7                           VARCHAR(5),
    hcpcs_cd_8                           VARCHAR(5),
    hcpcs_cd_9                           VARCHAR(5),
    hcpcs_cd_10                          VARCHAR(5),
    hcpcs_cd_11                          VARCHAR(5),
    hcpcs_cd_12                          VARCHAR(5),
    hcpcs_cd_13                          VARCHAR(5),
    hcpcs_cd_14                          VARCHAR(5),
    hcpcs_cd_15                          VARCHAR(5),
    hcpcs_cd_16                          VARCHAR(5),
    hcpcs_cd_17                          VARCHAR(5),
    hcpcs_cd_18                          VARCHAR(5),
    hcpcs_cd_19                          VARCHAR(5),
    hcpcs_cd_20                          VARCHAR(5),
    hcpcs_cd_21                          VARCHAR(5),
    hcpcs_cd_22                          VARCHAR(5),
    hcpcs_cd_23                          VARCHAR(5),
    hcpcs_cd_24                          VARCHAR(5),
    hcpcs_cd_25                          VARCHAR(5),
    hcpcs_cd_26                          VARCHAR(5),
    hcpcs_cd_27                          VARCHAR(5),
    hcpcs_cd_28                          VARCHAR(5),
    hcpcs_cd_29                          VARCHAR(5),
    hcpcs_cd_30                          VARCHAR(5),
    hcpcs_cd_31                          VARCHAR(5),
    hcpcs_cd_32                          VARCHAR(5),
    hcpcs_cd_33                          VARCHAR(5),
    hcpcs_cd_34                          VARCHAR(5),
    hcpcs_cd_35                          VARCHAR(5),
    hcpcs_cd_36                          VARCHAR(5),
    hcpcs_cd_37                          VARCHAR(5),
    hcpcs_cd_38                          VARCHAR(5),
    hcpcs_cd_39                          VARCHAR(5),
    hcpcs_cd_40                          VARCHAR(5),
    hcpcs_cd_41                          VARCHAR(5),
    hcpcs_cd_42                          VARCHAR(5),
    hcpcs_cd_43                          VARCHAR(5),
    hcpcs_cd_44                          VARCHAR(5),
    hcpcs_cd_45                          VARCHAR(5),
    PRIMARY KEY (desynpuf_id, clm_id, segment)
);

CREATE INDEX IF NOT EXISTS idx_claims_desynpuf_id ON inpatient_claims (desynpuf_id);
